package com.goBhutan.adminPanel.notification.enums;
public enum NotificationCategory {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    BUS_SCHEDULE_CHANGED,
    THEATER_SHOW_REMINDER,
    HOTEL_BOOKING_UPDATE,
    GAS_DELIVERY_UPDATE,
    SYSTEM_ALERT,
    PROMOTIONAL,
    CUSTOM
}
