spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/drakpa
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8085
  
jwt:
  auth:
    converter:
      resource-id: drakpa-rest-api
      principle-attribute: preferred_username